import '../../colors.css';

export const styles = {
  hero: {
    position: 'relative',
    width: '100%',
    height: '100vh',
    minHeight: { xs: 350, md: 500 },
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: { xs: 'center', md: 'flex-start' },
    
  },
  heroCard: {
    position: 'relative',
    maxWidth: 480,
    p: { xs: 3, md: 5 },
    m: 2,
    background: 'var(--color-bg)',
    boxShadow: '0 8px 32px rgba(0,0,0,0.12)',
    borderRadius: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    ml: { xs: 0, md: 8 },
  },
  heroTitle: {
    fontWeight: 700,
    color: 'var(--color-text)',
  },
  heroHighlight: {
    color: 'var(--color-primary)',
    fontWeight: 700,
    mb: 2,
    background: 'rgba(0, 191, 255, 0.1)',
    padding: '4px 0.5rem',
    borderRadius: 3,
    display: 'inline-block',
  },
  heroButton: {
    borderRadius: 999,
    fontWeight: 600,
    width: '70%',
    height: 50,
    alignSelf: 'center',
    background: 'var(--color-accent)',
    color: 'var(--color-bg)',
    fontSize: '1.5rem',
    padding: '1.2rem 2.8rem',
    boxShadow: '0 2px 8px rgba(255, 127, 50, 0.15)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '2rem',
    '&:hover': {
      background: 'var(--color-primary)',
    },
  },
  mainSection: {
    maxWidth: 1200,
    mx: 'auto',
    mt: { xs: 4, md: 8 },
    mb: 6,
    px: 2,
  },
  expectTitle: {
    fontWeight: 700,
    mb: 2,
  },
  expectText: {
    mb: 2,
  },
  programTitle: {
    fontWeight: 700,
    mb: 2,
  },
  timelineWrapper: {
    position: 'relative',
    pl: 3,
  },
  timelineLine: {
    position: 'absolute',
    left: 10,
    top: 0,
    bottom: 0,
    width: 4,
    background: 'var(--color-primary)',
    borderRadius: 2,
    opacity: 0.2,
  },
  timelineDot: {
    position: 'absolute',
    left: -2,
    top: 8,
    width: 16,
    height: 16,
    background: 'var(--color-primary)',
    borderRadius: '50%',
    border: '3px solid #fff',
    zIndex: 1,
  },
  timelineCard: {
    p: 2,
    ml: 4,
    background: 'var(--color-bg-secondary)',
  },
  gallerySection: {
    maxWidth: 1200,
    mx: 'auto',
    mb: 6,
    px: 2,
  },
  galleryImg: {
    width: '100%',
    borderRadius: 8,
  },
  backButtonSection: {
    maxWidth: 1200,
    mx: 'auto',
    mb: 4,
    px: 2,
  },
  masonryGallery: {
    columnCount: { xs: 1, sm: 2, md: 3 },
    columnGap: "16px",
    width: "100%",
    maxWidth: 1200,
    margin: "0 auto 48px auto",
    px: 2,
  },
  masonryItem: {
    breakInside: "avoid",
    marginBottom: "16px",
    width: "100%",
  },
};